name: teammlg-project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13.2
  - pip:
      - ollama==0.4.7
      - beautifulsoup4==4.13.3
      - requests==2.32.3