name: teammlg-project
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip<25.1
  - python=3.10
  - spacy-model-en_core_web_trf
  - pytextrank
  - scikit-learn
  - evaluate
  - pip:
      - ollama
      - beautifulsoup4==4.13.3
      - requests==2.32.3
      - nltk==3.9.1
      - numpy>=2.0.0
      - spacy
      - transformers
      - spacy-transformers
      - rouge_score
      - absl-py
      - wikipedia
      - accelerate
