#from sentence_transformers import SentenceTransformer, util
#from bert_score import score

import asyncio
from ragas import SingleTurnSample, evaluate
from ragas.llms import LangchainLLMWrapper
import ragas.metrics as ragasMetric
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

import os

# conda install ragas
# pip install bert_score
# pip install -U sentence-transformers
# pip install -U langchain-community

class Metrics:
    def __init__(self):
        pass

    def get_sentence_transformer_list(self):
        """
        https://www.sbert.net/docs/sentence_transformer/pretrained_models.html
        Sorted by average performance
        """
        return ["all-mpnet-base-v2", "multi-qa-mpnet-base-dot-v1", "all-distilroberta-v1",
                "all-MiniLM-L12-v2", "multi-qa-distilbert-cos-v1", "all-MiniLM-L6-v2",
                "multi-qa-MiniLM-L6-cos-v1", "paraphrase-multilingual-mpnet-base-v2",
                "paraphrase-albert-small-v2", "paraphrase-multilingual-MiniLM-L12-v2",
                "paraphrase-MiniLM-L3-v2", "distiluse-base-multilingual-cased-v1",
                "distiluse-base-multilingual-cased-v2"]

    def evaluate_embeddings(self, embedding1, embedding2, model_name="all-MiniLM-L6-v2"):
        """
        Uses 'all-MiniLM-L6-v2' by default, because its fast
        """
        #model = SentenceTransformer(model_name)
        #emb1 = model.encode(embedding1, convert_to_tensor=True)
        #emb2 = model.encode(embedding2, convert_to_tensor=True)
        #return self.similarity(emb1, emb2)
        pass

    def similarity(self, embedding1, embedding2):
        return util.cos_sim(embedding1, embedding2).item()

    def measure_faithfulness(self):
        pass

    def measure_semantic_similarity(selfs):
        pass

# OUTDATED - I left this here just in case we need it for later use
# various metrics we can use for evaluation 
# available data is: user query, model's reply, context (generated by RAG)

"""def tf_idf_qr(query, replies):
    tfidf = TfidfVectorizer()
    result = tfidf.fit_transform(replies)
    #for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    #    print(ele1, ':', ele2)
    #print(result.toarray())
    return str(result.toarray())

def tf_idf_qc(query, context):
    return 0

def tf_idf_rc(reply, context):
    return 0

def rougeL(predictions, references):
    rouge = evaluate.load('rouge')
    results = rouge.compute(predictions=predictions, references=references, rouge_types=['rougeL'])
    score = results['rougeL']
    return score

def bleu(predictions, references):
    bleu = evaluate.load('bleu')
    results = bleu.compute(predictions=predictions, references=references)
    score = results['bleu']
    return score"""

if __name__ == "__main__":

    metric = Metrics()

    e1 = "The sky is blue"
    e2 = "The sky is not blue"

    e1 = "The movie follows a young girl who discovers a magical portal in her backyard, leading her to a fantasy world where she must fight to save a kingdom from an ancient evil."
    e2 = "A young girl stumbles upon a mysterious gateway hidden in her backyard that transports her to an enchanted realm, where she embarks on a quest to defend the land from a long-forgotten dark force."

    e2 = "A young girl finds an old book buried in her backyard and begins a journey to uncover her family's secret history, which leads her to question everything she believed about her past."

    #res = metric.evaluate_embeddings(e1, e2)

    #P, R, F1 = score([e1], [e2], lang="en", verbose=True)

    #print("Precision:", P.item())
    #print("Recall:", R.item())
    #print("F1:", F1.item())

    #print(res)

    #sample = SingleTurnSample(
   #     question="Can you summarize the main themes of The Dark Knight for me?",
   ##     context=["The Dark Knight (2008), directed by Christopher Nolan, explores several deep and interconnected themes. The main ones include:\n\n\t1. Chaos vs. Order: The Joker represents chaos, anarchy, and unpredictability, while Batman and the authorities strive to maintain order. The film explores how fragile societal structures are when challenged by extreme forces.\n\n\t2. Moral Ambiguity and Duality: The film questions traditional notions of good and evil. Batman must bend ethical lines to fight crime, while Harvey Dent’s transformation into Two-Face shows how easily a hero can fall.\n\n\t3. Justice vs. Vengeance: Batman operates outside the law but seeks justice, whereas characters like Dent blur the line by giving in to vengeance when wronged.\n\n\t4. The Nature of Heroism: The film challenges the idea of what makes someone a hero. Batman chooses to be seen as a villain to protect Gotham's hope, highlighting the theme of self-sacrifice for the greater good.\n\n\t5. Fear and Corruption: Fear is used as both a weapon and a shield, while Gotham's institutions are portrayed as vulnerable to corruption—something both Batman and the Joker exploit in different ways."],
   #     answer="\n\n\"The Dark Knight\" explores several key themes:\n\n1. **Hero-Visa Duality**: Jack Nicholson, as the Dark Knight, seeks to protect others but ends up being harmed by a criminal gang that resembles the \"Kingsmen of the Dead.\"\n\n2. **Identity and Manipulation**: The film delves into how Jack sees himself\u2014both hero and villain\u2014and his actions sometimes seem manipulative.\n\n3. **Family Dynamics**: There's a tension between Jack and Harold Hurwitz, where Jack tries to protect others but may exploit their strength.\n\n4. **Power and Control**: The Gang's influence is both a threat and a source of strength for Jack, highlighting power dynamics within the narrative.\n\n5. **Social Commentary**: Despite its humor, \"The Dark Knight\" also touches on broader social issues, offering a critical look at the corrupting effects of certain behaviors.\n\nThese themes together create a complex exploration of Jack's multifaceted journey and his place in a world that feels both familiar and familiarized with his past."
    #)

    print("start")

    user_input = "Can you summarize the main themes of The Dark Knight for me?"
    contexts = ["Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker."]
    response="\n\n\"The Dark Knight\" explores several key themes:\n\n1. **Hero-Visa Duality**: Jack Nicholson, as the Dark Knight, seeks to protect others but ends up being harmed by a criminal gang that resembles the \"Kingsmen of the Dead.\"\n\n2. **Identity and Manipulation**: The film delves into how Jack sees himself\u2014both hero and villain\u2014and his actions sometimes seem manipulative.\n\n3. **Family Dynamics**: There's a tension between Jack and Harold Hurwitz, where Jack tries to protect others but may exploit their strength.\n\n4. **Power and Control**: The Gang's influence is both a threat and a source of strength for Jack, highlighting power dynamics within the narrative.\n\n5. **Social Commentary**: Despite its humor, \"The Dark Knight\" also touches on broader social issues, offering a critical look at the corrupting effects of certain behaviors.\n\nThese themes together create a complex exploration of Jack's multifaceted journey and his place in a world that feels both familiar and familiarized with his past."
    ground_truth = "The Dark Knight (2008), directed by Christopher Nolan, explores several deep and interconnected themes. The main ones include:\n\n\t1. Chaos vs. Order: The Joker represents chaos, anarchy, and unpredictability, while Batman and the authorities strive to maintain order. The film explores how fragile societal structures are when challenged by extreme forces.\n\n\t2. Moral Ambiguity and Duality: The film questions traditional notions of good and evil. Batman must bend ethical lines to fight crime, while Harvey Dent’s transformation into Two-Face shows how easily a hero can fall.\n\n\t3. Justice vs. Vengeance: Batman operates outside the law but seeks justice, whereas characters like Dent blur the line by giving in to vengeance when wronged.\n\n\t4. The Nature of Heroism: The film challenges the idea of what makes someone a hero. Batman chooses to be seen as a villain to protect Gotham's hope, highlighting the theme of self-sacrifice for the greater good.\n\n\t5. Fear and Corruption: Fear is used as both a weapon and a shield, while Gotham's institutions are portrayed as vulnerable to corruption—something both Batman and the Joker exploit in different ways."

    sample = SingleTurnSample(
        user_input=user_input,
        retrieved_contexts=contexts,
        response=response,
        reference=ground_truth
    )

    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    llm = LangchainLLMWrapper(llm)
    #messages = [HumanMessage(content="What's the weather like today?")]
    #response = llm.invoke(messages)
    #print(response.content)

    faithfulness = ragasMetric.FactualCorrectness(llm=llm)
    prompts = faithfulness.get_prompts()
    print(prompts.values())
    #score = asyncio.run(faithfulness.single_turn_ascore(sample))
    #print(score)
    #eval_llm = ChatOpenAI(model="gpt-3.5-turbo")

    pass






    #print(rougeL(["hello"], ["hello"]))

    #testquery = "Can you summarize the main themes of 28 years later for me?"
    #testreply = ["<think>\nAlright, let's tackle this user query. The user is asking for a summary of the main themes in the film titled \"28 Years Later.\" I'm looking at the data they've provided.\n\nFirst, I see that under 'tmdb_data,' there's information about '28 Years Later.' It mentions that it's 28 years later from the origin and shows some gameplay mechanics between a group on an island connected by a causeway. The overview talks about survivors on the island, their experiences during a mission into the mainland, and discovers various secrets and horrors.\n\nLooking at other entries in the data, there are '28 dienas v\\u0113l\\u0101k' which is about a zombie movie set during an apocalypse. The overview describes a movie where survivors attempt to escape, gaining abilities from watching it.\n\nIn the third entry, \"Red Dwarf: The 28-Years-Later Affair - Series XII,\" it's a documentary on the making of a specific Red Dwarf series. The overview mentions its focus on production details and the series' history up to that point.\n\nThe user wants a summary focusing on themes. I need to extract key elements from each entry. \"28 Years Later\" itself is 28 years later, so that's a main theme. Then there's gameplay mechanics in the first entry. The zombie movie has a focus on survival and overcoming the apocalypse. Lastly, the documentary deals with the production aspects of Red Dwarf.\n\nPutting it together, the themes are: time progression (28 years later), survival through adversity, and the nature of storytelling about media projects.\n</think>\n\nBased on the data provided, \"28 Years Later\" explores themes such as time progression in its narrative, survival experiences during a apocalypse, and the creation of media content about it."
                 #"<think>\nOkay, so the user is asking about when the \"28 years later\" film series will be released in their country. Let me look at the data provided.\n\nI see there's a section for \"28 years later,\" which includes several entries. Each entry has details like tmdb_data, popularity, release date, etc. But looking closer, I notice that some of these entries are just lists with no additional information beyond what's given in the data block.\n\nFor example:\n- One entry has an overview but it's cut off after \"It's been almost three decades...\". The rest have titles and release dates.\n- Other entries don't have any reviews or services listed. They only mention tmdb_data, which usually refers to TMDb, a popular video dataset.\n\nThe user is specifically asking about the release date in their country. But looking through the data, I can't find any release dates provided for this series. The last entry under \"28 years later\" has a release date of 2019-01-01 and no reviews or services listed.\n\nHmm, maybe the user expects me to infer based on some default or general knowledge. For instance, if I'm in a country that's not too far from the original release location (like the US), they might expect the series to be released around early 2025 since it's been almost three decades since the last movie in the trilogy. But without specific information, I can't confirm this.\n\nAlso, considering the data block has \"total_pages\" and \"total_results,\" but nothing about release dates or schedules. It seems like the only entry with a release date is one that was cut off, so I don't have any reliable info to go on.\n\nSo, in summary, based solely on the given data, there's no information provided about when \"28 years later\" will be released in the user's country. There might be some assumptions, but without explicit details, it's hard to give an accurate answer.\n</think>\n\nThe release date of \"28 Years Later\" isn't available from the provided data as it either has incomplete entries or no specific information about its release schedule.\n\nAnswer: The release date of \"28 Years Later\" is not available from the provided data."]

    #print(tf_idf_qr(testquery, testreply))

    #testreplies = ["dark knight is about many things", "sorry, can't help you"]
    #testgts = ["The Dark Knight is a pychological...", "I don't know the answer"]
    #print(rougeL(testreplies, testgts))
    #print(bleu(testreplies, testgts))
